name: ci 
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pages.yml'
      - 'docs/*'
      - 'mkdocs.yml'
      - 'Pipfile.lock'
      - 'Makefile'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install latest pipenv
      run: pip install -U pip pipenv

    - name: Install mkdocs dependencies
      run: make dev

    - name: Deploy to github pages
      run: make deploy
